#! /bin/sh

set -e

# conffiles must be moved before invoking rc.d
#DEBHELPER#

# This code should use dh_apache2 once it is available as build dependency

if [ "$1" = "configure" ] ; then
	if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
		if [ -z $EXPORT_APACHE2_MAINTSCRIPT_HELPER ] ; then
			. /usr/share/apache2/apache2-maintscript-helper
		fi
		apache2_invoke enconf apache2-doc || true
	fi
fi

exit
