#! /bin/sh

set -e

# This code should use dh_apache2 once it is available as build dependency

if [ "$1" = "purge" ] ; then
        if [ -x "/usr/sbin/a2disconf" ] ; then
                for S in apache2-doc ; do
                        /usr/sbin/a2disconf -q $S || true
                done

                if [ -x "/etc/init.d/apache2" ]; then
                      invoke-rc.d apache2 restart || true
                fi

        fi
fi

#DEBHELPER#

exit 0
