.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH A2ENCONF 8 "14 February 2012"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
a2enconf, a2disconf \- enable or disable an apache2 module
.SH SYNOPSIS
.B a2enmod
.RI [ configuration ]
.PP
.B a2dismod
.RI [ configuration ]
.SH DESCRIPTION
This manual page documents briefly the
.B a2enconf
and
.B a2disconf
commands.
.PP
.B a2enmod
is a script that enables the specified configuration file within the
.B apache2
configuration.  It does this by creating symlinks within
.BR /etc/apache2/conf-enabled .
Likewise,
.B a2disconf
disables a specific configuration part by removing those symlinks.  It is not an
error to enable a module which is already enabled, or to disable one which is
already disabled.
.PP
Note that many configuration file may have a dependency to specific modules.
Unlike module dependencies, these are not resolved automatically. Configuration
fragments stored in the conf-available directory are considered non-essential or
being installed and manged by reverse dependencies (e.g. web scripts).
.B apache2
.SH EXAMPLES
.RS
.B "a2enmod security"
.br
.B "a2dismod charset"
.RE
.PP
Enables Apache security directives stored in the
.B security
configuration files, and disables the
.B charset
configuration.
.SH FILES
.TP
.B /etc/apache2/conf-available
Directory with files giving information on available configuration files.
.TP
.B /etc/apache2/conf-enabled
Directory with links to the files in
.B conf-available
for enabled modules.
.SH "SEE ALSO"
.BR apache2ctl (8).
.SH AUTHOR
This manual page was written by Arno Toell <debian@toell.net> for the Debian
GNU/Linux distribution, as it is a Debian-specific script with the package.
